# Generated by Django 5.2.15 on 2026-07-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
