# Generated by Django 5.2.15 on 2026-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='Phonetic variants / common mispronunciations for STT, e.g. ["kalsoy", "cosign"] for Khao Soi'),
        ),
    ]
