# Generated by Django 5.2.15 on 2026-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='thai_name',
            field=models.CharField(blank=True, help_text='Thai script name, e.g. ข้าวซอย for Khao Soi. Used for matching when Thai speakers say the real name.', max_length=200),
        ),
    ]
