# Generated by Django 5.2.15 on 2026-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_menuitem_thai_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='clover_item_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Clover inventory item id used when pushing orders to Clover.', max_length=64),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='clover_modifiers',
            field=models.JSONField(blank=True, default=list, help_text='Rich Clover modifier-group structure (groups with kind/min/max and modifier ids/prices in cents).'),
        ),
        migrations.AddField(
            model_name='order',
            name='clover_error',
            field=models.TextField(blank=True, default='', help_text='Last Clover push error, for retry.'),
        ),
        migrations.AddField(
            model_name='order',
            name='clover_order_id',
            field=models.CharField(blank=True, default='', help_text='Clover order id returned when the order was pushed.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='clover_pushed',
            field=models.BooleanField(default=False, help_text='True when the order was successfully pushed to Clover.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list, help_text='Structured customization names the LLM emitted for this line (resolved to Clover modifier ids at push time).'),
        ),
    ]
